sass:
    sass_dir: assets/css

title: Moon Projects 
aboutme: [
  "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad ab amet facilis, maiores nam nisi ipsam libero error! Illum impedit libero animi facere officiis necessitatibus aperiam, suscipit voluptatem nemo laboriosam error aliquid expedita rem, ducimus dolore provident itaque similique perferendis ad maxime! Magni quam quidem explicabo exercitationem voluptate dignissimos dolore rerum provident iusto neque excepturi, minus soluta velit quia culpa.",
  "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore aliquam, fugiat provident ratione illum. Iure voluptatum, quasi iste debitis dignissimos voluptatem amet inventore. Nobis animi, eius labore deserunt consequuntur, tempora repudiandae aliquam harum sint deleniti facilis excepturi laudantium! Veniam repellendus itaque ad voluptatum, delectus debitis minus laborum soluta iste excepturi quae nemo natus reprehenderit modi a earum possimus facilis fugiat.",
]
references: [
  [
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit."
  ],
  [
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit."
  ],
  [
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit."
  ]
]