sass:
    sass_dir: assets/css

title: Moon Projects
icon: http://placehold.it/150x150.png
email: someemail@someprovider.com
mobile: 012 345 6789
phone: 012 345 6789
aboutme: [
  "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad ab amet facilis, maiores nam nisi ipsam libero error! Illum impedit libero animi facere officiis necessitatibus aperiam, suscipit voluptatem nemo laboriosam error aliquid expedita rem, ducimus dolore provident itaque similique perferendis ad maxime! Magni quam quidem explicabo exercitationem voluptate dignissimos dolore rerum provident iusto neque excepturi, minus soluta velit quia culpa.",
  "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore aliquam, fugiat provident ratione illum. Iure voluptatum, quasi iste debitis dignissimos voluptatem amet inventore. Nobis animi, eius labore deserunt consequuntur, tempora repudiandae aliquam harum sint deleniti facilis excepturi laudantium! Veniam repellendus itaque ad voluptatum, delectus debitis minus laborum soluta iste excepturi quae nemo natus reprehenderit modi a earum possimus facilis fugiat.",
]
references: [
  {
    quote: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat in aspernatur, quisquam, totam nulla vitae nemo a consequuntur pariatur id doloremque, officia.",
    person: "http://placehold.it/150x150"
  },{
    quote: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam quae, iure distinctio quas consequatur molestias architecto enim dolores, omnis ipsam, odio pariatur.",
    person: "http://placehold.it/150x150"
  },{
    quote: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, minus! Vel quidem delectus labore mollitia eligendi ab odio maiores? Ullam, nisi, blanditiis.",
    person: "http://placehold.it/150x150"
  },
]